# ./github/workflows/deploy.yml

name: Deploy Middleman to GH Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: Install packages
        run: |
          npm install
          bundle install

      - name: Build Middleman
        run: bundle exec middleman build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public